/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WestTabernacleChurchRouteImport } from './routes/west-tabernacle-church'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewLightChurchHangerHoustonRouteImport } from './routes/new-light-church-hanger-houston'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as HotelsOthersRouteImport } from './routes/hotels-others'
import { Route as HotelsAndInnsRouteImport } from './routes/hotels-and-inns'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HangarsRouteImport } from './routes/hangars'
import { Route as GeneralLightingRouteImport } from './routes/general-lighting'
import { Route as GeneralConstructionRouteImport } from './routes/general-construction'
import { Route as GeneralRouteImport } from './routes/general'
import { Route as EmbassyWoodlandsRouteImport } from './routes/embassy-woodlands'
import { Route as EmbassyCollegeStationRouteImport } from './routes/embassy-college-station'
import { Route as EllingtonAirfieldHangerRouteImport } from './routes/ellington-airfield-hanger'
import { Route as DominionChurchRouteImport } from './routes/dominion-church'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ChurchesRouteImport } from './routes/churches'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WestTabernacleChurchRoute = WestTabernacleChurchRouteImport.update({
  id: '/west-tabernacle-church',
  path: '/west-tabernacle-church',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewLightChurchHangerHoustonRoute =
  NewLightChurchHangerHoustonRouteImport.update({
    id: '/new-light-church-hanger-houston',
    path: '/new-light-church-hanger-houston',
    getParentRoute: () => rootRouteImport,
  } as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsOthersRoute = HotelsOthersRouteImport.update({
  id: '/hotels-others',
  path: '/hotels-others',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsAndInnsRoute = HotelsAndInnsRouteImport.update({
  id: '/hotels-and-inns',
  path: '/hotels-and-inns',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HangarsRoute = HangarsRouteImport.update({
  id: '/hangars',
  path: '/hangars',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralLightingRoute = GeneralLightingRouteImport.update({
  id: '/general-lighting',
  path: '/general-lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralConstructionRoute = GeneralConstructionRouteImport.update({
  id: '/general-construction',
  path: '/general-construction',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralRoute = GeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassyWoodlandsRoute = EmbassyWoodlandsRouteImport.update({
  id: '/embassy-woodlands',
  path: '/embassy-woodlands',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbassyCollegeStationRoute = EmbassyCollegeStationRouteImport.update({
  id: '/embassy-college-station',
  path: '/embassy-college-station',
  getParentRoute: () => rootRouteImport,
} as any)
const EllingtonAirfieldHangerRoute = EllingtonAirfieldHangerRouteImport.update({
  id: '/ellington-airfield-hanger',
  path: '/ellington-airfield-hanger',
  getParentRoute: () => rootRouteImport,
} as any)
const DominionChurchRoute = DominionChurchRouteImport.update({
  id: '/dominion-church',
  path: '/dominion-church',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchesRoute = ChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/churches': typeof ChurchesRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/dominion-church': typeof DominionChurchRoute
  '/ellington-airfield-hanger': typeof EllingtonAirfieldHangerRoute
  '/embassy-college-station': typeof EmbassyCollegeStationRoute
  '/embassy-woodlands': typeof EmbassyWoodlandsRoute
  '/general': typeof GeneralRoute
  '/general-construction': typeof GeneralConstructionRoute
  '/general-lighting': typeof GeneralLightingRoute
  '/hangars': typeof HangarsRoute
  '/home': typeof HomeRoute
  '/hotels-and-inns': typeof HotelsAndInnsRoute
  '/hotels-others': typeof HotelsOthersRoute
  '/lighting': typeof LightingRoute
  '/new-light-church-hanger-houston': typeof NewLightChurchHangerHoustonRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/west-tabernacle-church': typeof WestTabernacleChurchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/churches': typeof ChurchesRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/dominion-church': typeof DominionChurchRoute
  '/ellington-airfield-hanger': typeof EllingtonAirfieldHangerRoute
  '/embassy-college-station': typeof EmbassyCollegeStationRoute
  '/embassy-woodlands': typeof EmbassyWoodlandsRoute
  '/general': typeof GeneralRoute
  '/general-construction': typeof GeneralConstructionRoute
  '/general-lighting': typeof GeneralLightingRoute
  '/hangars': typeof HangarsRoute
  '/home': typeof HomeRoute
  '/hotels-and-inns': typeof HotelsAndInnsRoute
  '/hotels-others': typeof HotelsOthersRoute
  '/lighting': typeof LightingRoute
  '/new-light-church-hanger-houston': typeof NewLightChurchHangerHoustonRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/west-tabernacle-church': typeof WestTabernacleChurchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/churches': typeof ChurchesRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/dominion-church': typeof DominionChurchRoute
  '/ellington-airfield-hanger': typeof EllingtonAirfieldHangerRoute
  '/embassy-college-station': typeof EmbassyCollegeStationRoute
  '/embassy-woodlands': typeof EmbassyWoodlandsRoute
  '/general': typeof GeneralRoute
  '/general-construction': typeof GeneralConstructionRoute
  '/general-lighting': typeof GeneralLightingRoute
  '/hangars': typeof HangarsRoute
  '/home': typeof HomeRoute
  '/hotels-and-inns': typeof HotelsAndInnsRoute
  '/hotels-others': typeof HotelsOthersRoute
  '/lighting': typeof LightingRoute
  '/new-light-church-hanger-houston': typeof NewLightChurchHangerHoustonRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/west-tabernacle-church': typeof WestTabernacleChurchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/churches'
    | '/construction'
    | '/contact'
    | '/dominion-church'
    | '/ellington-airfield-hanger'
    | '/embassy-college-station'
    | '/embassy-woodlands'
    | '/general'
    | '/general-construction'
    | '/general-lighting'
    | '/hangars'
    | '/home'
    | '/hotels-and-inns'
    | '/hotels-others'
    | '/lighting'
    | '/new-light-church-hanger-houston'
    | '/projects'
    | '/services'
    | '/west-tabernacle-church'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/churches'
    | '/construction'
    | '/contact'
    | '/dominion-church'
    | '/ellington-airfield-hanger'
    | '/embassy-college-station'
    | '/embassy-woodlands'
    | '/general'
    | '/general-construction'
    | '/general-lighting'
    | '/hangars'
    | '/home'
    | '/hotels-and-inns'
    | '/hotels-others'
    | '/lighting'
    | '/new-light-church-hanger-houston'
    | '/projects'
    | '/services'
    | '/west-tabernacle-church'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/churches'
    | '/construction'
    | '/contact'
    | '/dominion-church'
    | '/ellington-airfield-hanger'
    | '/embassy-college-station'
    | '/embassy-woodlands'
    | '/general'
    | '/general-construction'
    | '/general-lighting'
    | '/hangars'
    | '/home'
    | '/hotels-and-inns'
    | '/hotels-others'
    | '/lighting'
    | '/new-light-church-hanger-houston'
    | '/projects'
    | '/services'
    | '/west-tabernacle-church'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChurchesRoute: typeof ChurchesRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  DominionChurchRoute: typeof DominionChurchRoute
  EllingtonAirfieldHangerRoute: typeof EllingtonAirfieldHangerRoute
  EmbassyCollegeStationRoute: typeof EmbassyCollegeStationRoute
  EmbassyWoodlandsRoute: typeof EmbassyWoodlandsRoute
  GeneralRoute: typeof GeneralRoute
  GeneralConstructionRoute: typeof GeneralConstructionRoute
  GeneralLightingRoute: typeof GeneralLightingRoute
  HangarsRoute: typeof HangarsRoute
  HomeRoute: typeof HomeRoute
  HotelsAndInnsRoute: typeof HotelsAndInnsRoute
  HotelsOthersRoute: typeof HotelsOthersRoute
  LightingRoute: typeof LightingRoute
  NewLightChurchHangerHoustonRoute: typeof NewLightChurchHangerHoustonRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  WestTabernacleChurchRoute: typeof WestTabernacleChurchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/west-tabernacle-church': {
      id: '/west-tabernacle-church'
      path: '/west-tabernacle-church'
      fullPath: '/west-tabernacle-church'
      preLoaderRoute: typeof WestTabernacleChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-light-church-hanger-houston': {
      id: '/new-light-church-hanger-houston'
      path: '/new-light-church-hanger-houston'
      fullPath: '/new-light-church-hanger-houston'
      preLoaderRoute: typeof NewLightChurchHangerHoustonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels-others': {
      id: '/hotels-others'
      path: '/hotels-others'
      fullPath: '/hotels-others'
      preLoaderRoute: typeof HotelsOthersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels-and-inns': {
      id: '/hotels-and-inns'
      path: '/hotels-and-inns'
      fullPath: '/hotels-and-inns'
      preLoaderRoute: typeof HotelsAndInnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangars': {
      id: '/hangars'
      path: '/hangars'
      fullPath: '/hangars'
      preLoaderRoute: typeof HangarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-lighting': {
      id: '/general-lighting'
      path: '/general-lighting'
      fullPath: '/general-lighting'
      preLoaderRoute: typeof GeneralLightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-construction': {
      id: '/general-construction'
      path: '/general-construction'
      fullPath: '/general-construction'
      preLoaderRoute: typeof GeneralConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general': {
      id: '/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof GeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassy-woodlands': {
      id: '/embassy-woodlands'
      path: '/embassy-woodlands'
      fullPath: '/embassy-woodlands'
      preLoaderRoute: typeof EmbassyWoodlandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embassy-college-station': {
      id: '/embassy-college-station'
      path: '/embassy-college-station'
      fullPath: '/embassy-college-station'
      preLoaderRoute: typeof EmbassyCollegeStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ellington-airfield-hanger': {
      id: '/ellington-airfield-hanger'
      path: '/ellington-airfield-hanger'
      fullPath: '/ellington-airfield-hanger'
      preLoaderRoute: typeof EllingtonAirfieldHangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominion-church': {
      id: '/dominion-church'
      path: '/dominion-church'
      fullPath: '/dominion-church'
      preLoaderRoute: typeof DominionChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churches': {
      id: '/churches'
      path: '/churches'
      fullPath: '/churches'
      preLoaderRoute: typeof ChurchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChurchesRoute: ChurchesRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  DominionChurchRoute: DominionChurchRoute,
  EllingtonAirfieldHangerRoute: EllingtonAirfieldHangerRoute,
  EmbassyCollegeStationRoute: EmbassyCollegeStationRoute,
  EmbassyWoodlandsRoute: EmbassyWoodlandsRoute,
  GeneralRoute: GeneralRoute,
  GeneralConstructionRoute: GeneralConstructionRoute,
  GeneralLightingRoute: GeneralLightingRoute,
  HangarsRoute: HangarsRoute,
  HomeRoute: HomeRoute,
  HotelsAndInnsRoute: HotelsAndInnsRoute,
  HotelsOthersRoute: HotelsOthersRoute,
  LightingRoute: LightingRoute,
  NewLightChurchHangerHoustonRoute: NewLightChurchHangerHoustonRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  WestTabernacleChurchRoute: WestTabernacleChurchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
